name: CI/CD

on:
  push:
    branches:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install sshpass
        run: |
          sudo apt-get install -y sshpass

      - name: Install antora
        run: |
          npm install -g @antora/cli @antora/site-generator-default

      - name: Run antora
        run: |
          antora ./antora-playbook.yml

      #      - name: Install SSH key
      #        uses: shimataro/ssh-key-action@v2
      #        with:
      #          key: ${{ secrets.SSH_PRIVATE_KEY }}
      #          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # very unelegant, but hoster does not support SSH key authentication :-/
      - name: Rsync to Webspace
        run: sshpass -p ${{secrets.SSH_PASSWORD}} rsync -av build/ ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOSTNAME}}:/var/www/web25462234/html/docs.my-agrirouter.com
